---
# defaults file for centos7_start
#
python_version: 3.9.9
python_download_url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
python_home: "/opt/python"
install_python: (true|bool)
django_path: "/opt/djangoprod"
